# Generated by Django 5.1.3 on 2024-12-15 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(blank=True, help_text='number of repetitions', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='execution time in seconds', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_workout_programs', to='user.clientuser')),
                ('exercises', models.ManyToManyField(related_name='workout_programs', through='workout.WorkoutExercise', to='exercise.exercise')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_workout_programs', to='user.traineruser')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_workout_plans', to='user.clientuser')),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_plans', to='workout.workoutprogram')),
            ],
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutprogram'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout_program', 'exercise'), name='unique_exercise_in_workout_program'),
        ),
    ]
