# Generated by Django 5.1.3 on 2024-12-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutplan',
            unique_together={('client', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutprogram',
            unique_together={('client', 'name')},
        ),
    ]
